services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    networks:
      - diesel_network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8505:8501"
    depends_on:
      - backend
    networks:
      - diesel_network
    restart: unless-stopped

networks:
  diesel_network:
    driver: bridge
